"""initial migration

Revision ID: 207c9c54a8f1
Revises: 
Create Date: 2024-02-25 10:20:55.824562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207c9c54a8f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_gachas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('used', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_gachas')
    # ### end Alembic commands ###
